id: select_framework
learningObjectives:
hints: []

# hack to skip the framework selection (since we only have Python), and add the files before we create the user's repo
startFlow:
  do:
    - actionId: github_commit_file
      params:
        file: "${tokenizer.ipynb}"
    - actionId: github_commit_file
      params:
        file: "${word_prediction.ipynb}"
    - actionId: github_commit_file
      params:
        file: "${question_answering.ipynb}"
    - actionId: update_user_props
      params:
        field: "frameworks.backend"
        value: "python"
    - actionId: finish_step

# should not get there
trigger:
  type: chat_form_submitted
  params:
    formId: backend_message_form
  flowNode:
    do:
      - actionId: finish_step
