id: from_pretraining_to_fine_tuning
learningObjectives:
  - Understand the training stages of LLMs, emphasizing pretraining and fine-tuning.
hints: []
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Let's delve into the life cycle of Large Language Models, a journey through pretraining and fine-tuning.
          - text: Imagine teaching an AI everything - that's pretraining, where a broad spectrum of data equips models with fundamental knowledge.
          - text: Fine-tuning then hones this knowledge for specific tasks, like an artist refining their skills to master their craft.
          - text: This process turns a generalized model into a tool tailored for targeted applications, harnessing its trained capabilities to solve real-world problems.
          - text: Consider how pretraining provides the model with basic language understanding, while fine-tuning focuses on application-specific performance.
          - text: With that understanding established, let's continue exploring how these models evolve through training!
          - text: "Resource: Chapter 4 - Pretraining and Fine-tuning in 'Hands-On Large Language Models'"
    - actionId: ready_message
      params:
        person: lucca
trigger:
  type: user_ready_response
  flowNode:
    do:
      - actionId: finish_step
